parameters:
    user_media_hashids_salt: '%env(USER_MEDIA_HASHIDS_SALT)%'

services:
    GaylordP\UserMediaBundle\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']
        autoconfigure: true
        autowire: true

    GaylordP\UserMediaBundle\EventListener\UserMediaListener:
        arguments:
            - '%user_media_hashids_salt%'
        tags:
            -
                name: 'doctrine.event_listener'
                event: 'postPersist'

    GaylordP\UserMediaBundle\Provider\UserMediaProvider:
        arguments:
            - '@security.helper'
            - '@GaylordP\UserMediaBundle\Repository\UserMediaLikeRepository'
            - '@GaylordP\UserMediaBundle\Repository\UserMediaCommentRepository'

    GaylordP\UserMediaBundle\Repository\UserMediaCommentRepository:
        arguments:
            - '@doctrine'
        tags:
            - 'doctrine.repository_service'

    GaylordP\UserMediaBundle\Repository\UserMediaLikeRepository:
        arguments:
            - '@doctrine'
        tags:
            - 'doctrine.repository_service'

    GaylordP\UserMediaBundle\Twig\Extension:
        arguments:
            - '@request_stack'
            - '%user_media%'
        tags:
            - 'twig.extension'

    GaylordP\UserMediaBundle\UserNotificationFormat\UserMediaNotificationFormat:
        arguments:
            - '@translator'
            - '@GaylordP\UserMediaBundle\Repository\UserMediaLikeRepository'
        tags:
            - 'user.notification_format'
