services:
    GaylordP\UserMediaBundle\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']
        autoconfigure: true
        autowire: true

    GaylordP\UserMediaBundle\Twig\Extension:
        arguments:
            - '@request_stack'
            - '%user_media%'
        tags:
            - 'twig.extension'
